package demo.testbuild;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pojo2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String field2;

	public Pojo2() {
	}

	public java.lang.String getField2() {
		return this.field2;
	}

	public void setField2(java.lang.String field2) {
		this.field2 = field2;
	}

	public Pojo2(java.lang.String field2) {
		this.field2 = field2;
	}

}