package demo.testbuild;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pojo1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;
error
	private java.lang.String field1;

	public Pojo1() {
	}

	public java.lang.String getField1() {
		return this.field1;
	}

	public void setField1(java.lang.String field1) {
		this.field1 = field1;
	}

	public Pojo1(java.lang.String field1) {
		this.field1 = field1;
	}

}
